name: Deploy pra prod

on:
  push:
    branchs:
      - main
jobs:
  upload_to_homolog:
    runs-on: self-hosted
    steps:
      - name: "Iniciando JOB"
        run: | 
          echo "inicando JOB em %(date)"
      - name: "Checkout codigo"
        uses: actions/checkout@v4
      - name: "Configurar Ambiente"
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: "Instalar Dependencias"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN}} | docker login --username ${{secrets.DOCKERHUB_USER}} --password-stdin"
      - name: Docker Build
        run: docker build . -t jonesparanhos/flask-acme:latest    
      - name: Docker Push
        run: docker push jonesparanhos/flask-acme:latest
      - name: Install kubectl
        uses: Azure/setup-kubectl@v3
        with:
        version: 'v1.29.2
      - name: Deploy K8s
        run: kubectl rollout restart deploy flask-acme -n acme
     