name: Testar_Noturno

on:
  schedule:
    - cron: '0 23 * * * '
  push:
    branches:
      - main
jobs:
  teste_norturno:
    runs-on: self-hosted
    steps:
      - name: "Iniciando JOB"
        run: | 
          echo "inicando JOB em %(date)"
      - name: "Checkout codigo"
        uses: actions/checkout@v4
      - name: "Configurar Ambiente"
        uses: actions/setup-python@v5
      - name: "Instalar Dependencias"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt